app/urls.py
from django.urls import path     
from . import views_forms

app_name = 'books'

urlpatterns = [
    path('', views_forms.main, name='main' ),
    path('login', views_forms.login, name='login'),
    path('exit', views_forms.logout, name='logout'),
    path('books', views_forms.mybooks, name='mybooks'),
    path('books/<int:id>/delRelUsBK', views_forms.unFavourite, name='deleteRelBookUser'),
    path('books/<int:id>', views_forms.bookDetail, name='bookDetail'),
    path('books/<int:id>/delete', views_forms.delete, name='deleteBook'),
    path('books/<int:id>/relBookUser', views_forms.relationBookToUser, name='relBookUser'),



]

ayudante/urls.py
from django.urls import path     
from . import views_forms

app_name = 'ayudante'

urlpatterns = [
    path('', views_forms.main, name='main' ),
    path('login', views_forms.login, name='login'),
    path('exit', views_forms.logout, name='logout'),
    path('dashboard', views_forms.dashboard, name='dashboard'),
    path('addJob', views_forms.addJob, name='addJob'),
    path('showJob/<int:id>', views_forms.showJob, name='showJob'),
    path('edit/<int:id>', views_forms.editJob, name='editJob'),
    path('delete/<int:id>', views_forms.deleteJob, name='deleteJob'),
    path('doneJob/<int:id>', views_forms.doneJob, name='doneJob'),
    path('asignJob/<int:id>', views_forms.asignJob, name='asignJob'),
]

librosFav/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('deseos/', include('deseos.urls')),
    path('ayudante/', include('ayudante.urls')),
    path('', include('baby.urls')),
]

ayudante/models.py
from tkinter import CASCADE
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=50, unique=True)
    password = models.CharField(max_length=100, verbose_name='contrasenia')

    def __str__(self):
        return f'{self.first_name} , {self.last_name}'

class Job(models.Model):
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=200)
    description = models.TextField()
    userJob = models.ForeignKey(User,related_name='jobs',on_delete=models.CASCADE, null=True)
    created_by = models.ForeignKey(User,related_name='jobs_created_by',on_delete=models.CASCADE, default=None)

ayudante/templates/ayudante/addJob.html
{% extends "app/index.html" %}
{% block title%}Add Job{%endblock%}
{% block content%}
<div class="d-flex justify-content-between bg-dark text-light ">

    <h1 class="m-4 "><span class="fa fa-user-circle"></span>Add Job</h1>
    <div class="d-flex">
        <h1 class="m-4 "><a href="{% url 'ayudante:dashboard' %}">Back</a></h1>
        <h1 class="m-4 "><a href="{% url 'ayudante:logout' %}">Salir</a></h1>
    </div>

    
</div>

<div class="w-75 d-flex justify-content-start p-5">
    <form action="" method="post">

        {% csrf_token %}
        {{ jobForm.non_field_errors }}

        {% for field in jobForm %}
        <div class="mb-3 row">


            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
            <div class="col-sm-9">
                {{ field }}
            </div>

            {% if field.errors %}

            <div class="alert alert-danger mt-2" role="alert">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>

            {% endif %}

            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <div class="container fs-3 d-flex justify-content-center">
            <div class="d-flex ">
                <a href="{% url 'ayudante:dashboard' %}" class="btn btn-light m-1">Cancel</a>
            </div>
            <div class="d-flex ">
                <form action="{% url 'ayudante:addJob' %}" method="post">
                    <button class="btn btn-warning m-1" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </form>
</div>


{% endblock %}

ayudante/templates/ayudante/dashboard.html
{% extends "app/index.html" %}
{% block title%}dashboard{%endblock%}
{% block content%}
<div class="d-flex justify-content-between bg-dark text-light ">

    <h1 class="m-4 "><span class="fa fa-user-circle"></span> Bienvenido {{request.session.usuario.nombre}}
        {{request.session.usuario.apellido}}!</h1>
    <div class="d-flex align-items-center">
        <h1 class="m-2"><a href="{% url 'ayudante:logout' %}">Logout</a></h1>
        <h1 class="m-2"><a href="{% url 'ayudante:addJob' %}" class="btn btn-warning fs-3">Add Job</a></h1>
    </div>

</div>

<div class="d-flex m-1 justify-content-around">
        <div class="container">
            <div class="d-flex align-items-center py-3">
                <h1>All Jobs <span class="fa fa-briefcase"> </span></h1>
            </div>
            <table class="table table-striped col-10 ">
                <thead>
                    <tr>

                        <th scope="col">Job</th>
                        <th scope="col">Location</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="fs-5">
                    {% for job in jobs%}

                    <tr>

                        <td>{{job.title}}</td>
                        <td>{{job.location}}</td>
                        <td >
                            <a href="{% url 'ayudante:showJob' id=job.id %}" class="mx-1 fa fa-eye btn btn-primary "></a>
                            <a href="{% url 'ayudante:asignJob' id=job.id %}" class="mx-1 fa fa-plus-circle btn btn-success "> Add to my jobs</a>
                            {% if job.created_by == user %}
                            <a href="{% url 'ayudante:editJob' id=job.id %}" class="mx-1 fa fa-pencil-square-o btn btn-warning "></a>
                            <a href="" class="mx-1 fa fa-trash btn btn-danger" data-bs-toggle="modal"
                                data-bs-target="#myModal{{job.id}}"></a>
                            {% endif %}
                        </td>

                        <!-- The Modal -->
                        <div class="modal fade" id="myModal{{job.id}}">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h4 class="modal-title text-danger ">ALERTA</h4>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                    </div>

                                    <!-- Modal body -->
                                    <div class="modal-body">
                                        Esta a punto de borrar: {{job.title}}
                                    </div>

                                    <!-- Modal footer -->
                                    <div class="modal-footer">
                                        <form action="{% url 'ayudante:deleteJob' id=job.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger"
                                                data-bs-dismiss="modal">Eliminar</button>
                                        </form>
                                        <button type="button" class="btn btn-light"
                                            data-bs-dismiss="modal">Cancelar</button>
                                    </div>

                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </tr>
                </tbody>
            </table>
        </div>

        <div class="container">

            <div class="d-flex align-items-center py-3">
                <h1>My Jobs <span class="fa fa-briefcase"> </span> </h1>
            </div>
            <table class="table table-striped col-10 ">
                <thead>
                    <tr>
                        <th scope="col">Job Name</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="fs-5">
                    {% for job in myAsignedJobs%}
                    <tr>
                        <td>{{job.title}}</td>

                        <td>
                                <a href="{% url 'ayudante:showJob' id=job.id %}" class="mx-1 fa fa-eye btn btn-primary"></a>
                                <a href="{% url 'ayudante:doneJob' id=job.id %}" class="btn btn-success fa fa-check-circle" data-bs-toggle="modal"
                                data-bs-target="#myModalDone{{job.id}}" > Done! </a>
                        </td>

                    </tr>
                    <!-- The Modal -->
                    <div class="modal fade" id="myModalDone{{job.id}}">
                        <div class="modal-dialog">
                            <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title text-success ">Confirmar</h4>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    Se ha culminado con la tarea: {{job.title}} ?
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <form action="{% url 'ayudante:doneJob' id=job.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-success"
                                            data-bs-dismiss="modal">Finalizada</button>
                                    </form>
                                    <button type="button" class="btn btn-light"
                                        data-bs-dismiss="modal">Cancelar</button>
                                </div>

                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>



{% endblock %}

ayudante/templates/ayudante/editJob.html
{% extends "app/index.html" %}
{% block title%}makeWish{%endblock%}
{% block content%}
<div class="d-flex justify-content-between bg-dark text-light ">

    <h1 class="m-4 "> <span class="fa fa-pencil-square-o"> </span> Edit your job </h1>
    <div class="d-flex">
        <h1 class="m-4 "><a href="{% url 'ayudante:dashboard' %}">Back</a></h1>
        <h1 class="m-4 "><a href="{% url 'ayudante:logout' %}">Salir</a></h1>
    </div>
    
</div>

<div class="w-75 d-flex justify-content-start p-5">
    <form action="" method="post">

        {% csrf_token %}
        {{ jobForm.non_field_errors }}

        {% for field in jobForm %}
        <div class="mb-3 row">


            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
            <div class="col-sm-9">
                {{ field }}
            </div>

            {% if field.errors %}

            <div class="alert alert-danger mt-2" role="alert">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>

            {% endif %}

            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <div class="container fs-3 d-flex justify-content-center">
            <div class="d-flex ">
                <a href="{% url 'ayudante:dashboard' %}" class="btn btn-light m-1">Cancel</a>
            </div>
            <div class="d-flex ">
                <form action="" method="post">
                    <button class="btn btn-warning m-1" type="submit">Update</button>
                </form>
            </div>
        </div>
    </form>
</div>


{% endblock %}

ayudante/templates/ayudante/index.html
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
        <script src="https://use.fontawesome.com/682aac1834.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="  crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <title>{% block title%}Cursos{%endblock%}</title>
    </head>


<body>
    {% block content%}
    {% endblock %}
    <script>
        {% if messages %}
            {% for message in messages %}
                toastr.{{message.tags}}("{{ message }}")
            {% endfor %}
        {% endif %}
    </script>

</body>
</html>

ayudante/templates/ayudante/main.html
{% extends "app/index.html" %}
{% block title%}Ayudante APP{%endblock%}
{% block content%}
<div class="container d-flex flex-column" >
    <h1 class=" m-3 text-center">Welcome to Handy Helper! <span class="fa fa-star text-warning  "></span></h1>
    <div class="container d-flex">

        <div class="container">
            <div class="d-flex align-content-center justify-content-center ">
                <h1 class="m-2">Register</h1>
            </div>
            <div class="container">
                <hr>
            </div>
            
            <div class="container pb-5">
                <form action="{% url 'ayudante:main' %}" method="post">
            
                    {% csrf_token %}
                    {{ formRegister.non_field_errors }}
            
                    {% for field in formRegister %}
                    <div class="mb-3 row">
            
            
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-9">
                            {{ field }}
                        </div>
            
                        {% if field.errors %}
            
                        <div class="alert alert-danger mt-2" role="alert">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
            
                        {% endif %}
            
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    {% endfor %}
            
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-primary " type="submit">Enviar</button>
                    </div>
                </form>
            
            </div>
        </div>
        
        <div class="container">
            <div class="d-flex align-content-center justify-content-center ">
                <h1 class="m-2">Login</h1>
            </div>
            <div class="container">
                <hr>
            </div>
            
            <div class="container pb-5">
                <form action="{% url 'ayudante:login' %}" method="post">
            
                    {% csrf_token %}
                    {{ formLogin.non_field_errors }}
            
                    {% for field in formLogin %}
                    <div class="mb-3 row">
            
            
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-9">
                            {{ field }}
                        </div>
            
                        {% if field.errors %}
            
                        <div class="alert alert-danger mt-2" role="alert">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
            
                        {% endif %}
            
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    {% endfor %}
            
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-primary " type="submit">Enviar</button>
                    </div>
                </form>
            
            </div>
        </div>
    </div>
</div>





{% endblock %}

ayudante/templates/ayudante/showJob.html
{% extends "app/index.html" %}
{% block title%}Job Detail{%endblock%}
{% block content%}
<div class="d-flex justify-content-between bg-dark text-light ">
    <div>
        <h1 class="m-4 "><span class="fa fa-briefcase"></span> Job Detail</h1>
    </div>
    <div class=" d-flex  ">
        <h1 class="m-4 "><a href="{% url 'ayudante:dashboard' %}">Back</a></h1>
        <h1 class="m-4 "><a href="{% url 'ayudante:logout' %}">Logout</a></h1>
    </div>

</div>

<div class="w-75 d-flex flex-column justify-content-start p-5">

    <h1>{{job.title}}</h1>
    <h3>{{job.description}}</h3>
    <h3>{{job.location}}</h3>

    {% if job.userJob != user %}
    <a class="btn btn-success fa fa-plus w-25 fs-3"  href="{% url 'ayudante:asignJob' id=job.id %}">Add to my jobs</a>
    {% endif %}

</div>


{% endblock %}