app/urls.py
from django.urls import path     
from . import views_forms

app_name = 'books'

urlpatterns = [
    path('', views_forms.main, name='main' ),
    path('login', views_forms.login, name='login'),
    path('exit', views_forms.logout, name='logout'),
    path('books', views_forms.mybooks, name='mybooks'),
    path('books/<int:id>/delRelUsBK', views_forms.unFavourite, name='deleteRelBookUser'),
    path('books/<int:id>', views_forms.bookDetail, name='bookDetail'),
    path('books/<int:id>/delete', views_forms.delete, name='deleteBook'),
    path('books/<int:id>/relBookUser', views_forms.relationBookToUser, name='relBookUser'),



]

baby/urls.py
from django.urls import path     
from . import views_forms
from django.conf import settings
from django.conf.urls.static import static

app_name = 'baby'

urlpatterns = [
    path('login/', views_forms.login, name='login' ),
    path('logout/', views_forms.logout, name='logout' ),
    path('register/', views_forms.register, name='register' ),
    path('', views_forms.mainPage, name='mainPage' ),
    path('products/<str:size> ', views_forms.productBySize, name='productBySize'),
    path('products/<str:size>/<str:category> ', views_forms.productBySizeByCat, name='productBySizeByCat'),

    path('products/addToShoppingCart/<int:id>', views_forms.addToShoppingCart, name='addToShoppingCart'),
    path('shoppingCart/empty', views_forms.shoppingCartempty, name='shoppingCartempty'),
    path('shoppingCart/', views_forms.shoppingCart, name='shoppingCart'),
    path('shoppingCart/buy', views_forms.buy, name='buy'),

    path('products/', views_forms.productGrid, name='productGrid'),
    #Admin
    path('adminPage/', views_forms.adminMainPage, name='adminPage' ),
    path('adminPage/users', views_forms.showUsers, name='showUsers' ),
    path('adminPage/users/add', views_forms.addUserAdmin, name='addUser' ),
    path('adminPage/users/editUser/<int:id>', views_forms.editUser, name='editUser' ),
    path('adminPage/users/deleteUser/<int:id>', views_forms.deleteUser, name='deleteUser' ),
    path('adminPage/products', views_forms.adminShowProductsPage, name='showProducts' ),
    path('adminPage/products/add', views_forms.addProduct, name='addProduct' ),
    path('adminPage/products/edit/<int:id>', views_forms.editProd, name='editProd' ),
    path('adminPage/products/delete/<int:id>', views_forms.deleteProd, name='deleteProd' ),
    path('adminPage/products/detail/<int:id>', views_forms.showProductDetail, name='showProductDetail' ),
    path('adminPage/products/addCategory', views_forms.addCategory, name='addCategory' ),
    path('adminPage/products/editCat/<int:id>', views_forms.editCat, name='editCat' ),
    path('adminPage/products/deleteCat/<int:id>', views_forms.deleteCat, name='deleteCat' ),
    
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

librosFav/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('deseos/', include('deseos.urls')),
    path('ayudante/', include('ayudante.urls')),
    path('', include('baby.urls')),
]

baby/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.




class User(models.Model):
    TYPEUSER_CHOICES = (
        ('1','ADMINISTRADOR'),
        ('2','USUARIO'),
        ('3','ALMACENERO'),
    )

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=50, unique=True)
    password = models.CharField(max_length=100, verbose_name='contrasenia')
    baby_birthday = models.DateField(null=True, blank=True)
    typeUser = models.CharField(max_length=1, choices = TYPEUSER_CHOICES, default = '2', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} , {self.last_name}'

class Category(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    GENDER_CHOICES = (
    ('1','Niño'),
    ('2','Niña'),
    ('3','Unisex')
    )

    SIZE_CHOICES = (
    ('1','0-3 meses'),
    ('2','3-6 meses'),
    ('3','6-12 meses'),
    ('4','12-18 meses'),
    ('5','18-24 meses'),
    ('6','2 años'),
    ('7','3 años'),    
    )
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    img = models.ImageField(upload_to="images/", blank=True, null=True)
    size = models.CharField(max_length=50,choices=SIZE_CHOICES, default='0-6 meses')
    stock = models.IntegerField(default=1, null=False)
    prodCat = models.ForeignKey(Category, related_name='productos', on_delete=models.CASCADE)
    prodGender = models.CharField(max_length=1, choices = GENDER_CHOICES, default = '1')
    cantVendidos = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__ (self):
        return f'{self.name} - {self.prodCat.name} - {self.price} - {self.stock}'


class Boleta(models.Model):

    total = models.DecimalField(decimal_places=2, max_digits=6)
    totalDesc = models.DecimalField(decimal_places=2, max_digits=6, default=0)
    totalOpGravada = models.DecimalField(decimal_places=2, max_digits=6)
    totalIGV = models.DecimalField(decimal_places=2, max_digits=6)
    precioEnvio = models.DecimalField(decimal_places=2, max_digits=6, default = 10)
    #detalleBoleta=models.ManyToManyField(BoletaDetalle, related_name='carritos')
    users = models.ForeignKey(User, related_name='usuarios2', on_delete=models.CASCADE, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    pagado = models.BooleanField(default=False)

    def __str__ (self):
        return f'{self.users} - {self.pagado}'


class BoletaDetalle(models.Model):
    
    precioUni = models.DecimalField(decimal_places=2, max_digits=6, default=0)
    subtotal = models.DecimalField(decimal_places=2, max_digits=6)
    descuento = models.DecimalField(decimal_places=2, max_digits=6, default=0)
    opGravada = models.DecimalField(decimal_places=2, max_digits=6)
    igv = models.DecimalField(decimal_places=2, max_digits=6)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(User, related_name='usuarios', on_delete=models.CASCADE)
    productos = models.ForeignKey(Product, related_name='boletaDetalle', on_delete=models.CASCADE, default=0)
    cantidad = models.IntegerField(default=1, null=False)
    estado = models.BooleanField(default=False)
    boleta = models.ForeignKey(Boleta, related_name='boletas', on_delete=models.CASCADE, default =1)
    
    def __str__ (self):
        return f'{self.usuario} - {self.productos} - {self.cantidad} - {self.boleta.id}'

baby/views.py
from django.shortcuts import render

# Create your views here.

baby/templates/baby/addUser.html
{% extends "baby/indexAdmin.html" %}
{% block title%}Añadir Usuario{%endblock%}
{% block content%}

<h1 class="text-center">Agregar Usuario</h1>
<div class="d-flex justify-content-between p-5">

    <form class="container d-flex flex-column w-50 " action="" method="post">
        {% csrf_token %}
        {{ userForm.non_field_errors }}

        {% for field in userForm %}
        <div class="mb-3 row fs-4">
            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
            <div class="col-sm-9 fs-4">
                {{ field }}
            </div>

            {% if field.errors %}

            <div class="alert alert-danger mt-2" role="alert">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>

            {% endif %}

            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <div class="d-flex flex-column">
            <div class="container fs-3 d-flex justify-content-center">
                <div class="d-flex ">
                    <a href="{% url 'baby:showUsers'%}" class="btn btn-light m-1">Cancel</a>
                </div>
                <div class="d-flex ">
                    <form action="" method="post">
                        <button class="btn btn-warning m-1" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </form>
    {% load static %}
    <img class="halfImage " src="{% static 'img/babyClothesAdd.jpg' %}" alt="Error de carga, por favor actualizar">
</div>


{% endblock %}

baby/templates/baby/adminProductsPage.html
{% extends "baby/indexAdmin.html" %}
{% block title%}BabyShop Admin{%endblock%}
{% block content%}
<div class="">
    <h1 class="text-center">Lista de Productos</h1>
    <div class="d-flex py-4">
        <a href="{% url 'baby:addProduct' %}" class="mx-1 btn btn-success p-2 fs-4">Nuevo Producto <i class="fa-solid fa-circle-plus"></i></a>
    </div>
    <table id="myTable" class="display fs-4 ">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Price</th>
                <th>Categoria</th>
                <th>Género</th>
                <th>Talla</th>
                <th>Stock</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for product in productos %}
            <tr>
                <td>{{product.id }}</td>
                <td>{{product.name}}</td>
                <td>S/{{product.price}}</td>
                <td>{{product.prodCat}}</td>
                <td>{{product.get_prodGender_display}}</td>
                <td>{{product.get_size_display}}</td>
                <td>{{product.stock}}</td>

                <td>
                    <a href="{% url 'baby:showProductDetail' id=product.id %}" class="mx-1 fa fa-eye btn btn-info "></a>
                    <a href="{% url 'baby:editProd' id=product.id %}" class="mx-1 fa fa-pencil-square-o btn btn-warning "></a>
                    <a href="" class="mx-1 fa fa-trash btn btn-danger" data-bs-toggle="modal"
                        data-bs-target="#myModal{{product.id}}"></a>
                </td>
            </tr>
            <!-- The Modal -->
            <div class="modal fade" id="myModal{{product.id}}">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title text-danger ">ALERTA</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            Esta a punto de borrar: {{product.name}}
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <form action="{% url 'baby:deleteProd' id=product.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger"
                                    data-bs-dismiss="modal">Eliminar</button>
                            </form>
                            <a href="" class="btn btn-light"
                                data-bs-dismiss="modal">Cancelar</a>
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
        </tbody>
    </table>
</div>






{% endblock %}

baby/templates/baby/adminUsersPage.html
{% extends "baby/indexAdmin.html" %}
{% block title%}BabyShop Admin{%endblock%}
{% block content%}
<div class="">
    <h1 class="text-center">Lista de Usuarios</h1>
    <div class="d-flex py-4">
        <a href="{% url 'baby:addUser' %}" class="mx-1 btn btn-success p-2 fs-4">Nuevo Usuario <i class="fa-solid fa-circle-plus"></i></a>
    </div>
    <table id="myTable" class="display fs-4 ">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Cumple Bebe</th>
                <th>Tipo Usuario</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{user.id }}</td>
                <td>{{user.first_name}} {{user.last_name}}</td>
                <td>{{user.email}}</td>
                <td>{{user.baby_birthday}}</td>
                <td>{{user.get_typeUser_display}}</td>

                <td>
                    <a href="{% url 'baby:editUser' id=user.id %}" class="mx-1 fa fa-pencil-square-o btn btn-warning "></a>
                    <a href="" class="mx-1 fa fa-trash btn btn-danger" data-bs-toggle="modal"
                        data-bs-target="#myModal{{user.id}}"></a>
                </td>
            </tr>
            <!-- The Modal -->
            <div class="modal fade" id="myModal{{user.id}}">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title text-danger ">ALERTA</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            Esta a punto de borrar: {{user.first_name}} {{user.last_name}}
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <form action="{% url 'baby:deleteUser' id=user.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger"
                                    data-bs-dismiss="modal">Eliminar</button>
                            </form>
                            <a href="" class="btn btn-light"
                                data-bs-dismiss="modal">Cancelar</a>
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
        </tbody>
    </table>
</div>






{% endblock %}

baby/templates/baby/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/682aac1834.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"
        integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"
        integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8"
        src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="https://kit.fontawesome.com/2e11c35c7f.js" crossorigin="anonymous"></script>
    <!--<script src="{% static 'js/script.js' %}"></script>-->
    <title>{% block title%}BabyShop{%endblock%}</title>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
</head>


<body>
    {% block navbar%}
    <div class="allNavBar">
        <nav class="navbar navbar-expand-lg navbar-light colorGreenBaby">
            <div class="container-fluid">
                <a class="navbar-brand fs-2 text-white py-0 font-weight-bold" href="#">BabyShop <span
                        class="fa-solid fa-baby-carriage"></span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-flex justify-content-between " id="navbarSupportedContent">
                    <div>
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link fs-4 text-white mx-3 " aria-current="page" href="{% url 'baby:mainPage' %}">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link fs-4 text-white mx-3 " href="#">Sobre Nosotros</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle fs-4 text-white mx-3" href="{% url 'baby:productGrid' %}" id="navbarDropdown"
                                    role="button" data-bs-toggle="dropdown" >
                                    Productos
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><p class="mx-4 my-1">Edad del Bebé</p></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'baby:productBySize' size='1' %}">0-3 meses</a></li>
                                    <li><a class="dropdown-item" href="{% url 'baby:productBySize' size='2' %}">3-6 meses</a></li>
                                    <li><a class="dropdown-item" href="{% url 'baby:productBySize' size='3' %}">6-12 meses</a></li>
                                    <li><a class="dropdown-item" href="{% url 'baby:productBySize' size='4' %}">12-18 meses</a></li>
                                    <li><a class="dropdown-item" href="{% url 'baby:productBySize' size='5' %}">18-24 meses</a></li>
                                    <li><a class="dropdown-item" href="{% url 'baby:productBySize' size='6' %}">2 años</a></li>
                                    <li><a class="dropdown-item" href="{% url 'baby:productBySize' size='7' %}">3 años</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link fs-4 text-white mx-3 " href="#">Contáctanos</a>
                            </li>
                        </ul>

                    </div>
                    {% if request.session.usuario %}
                    <h2 class="fs-1 text-white mx-3">Bienvenida {{request.session.usuario.nombre}} {{request.session.usuario.apellido}}</h2>
                    {% if cart %}
                    <a class="text-white" href="{% url 'baby:shoppingCart' %}"><span
                            class=" fs-1 fa-solid fa-cart-shopping btn btn-warning "></span></a>
                    {% else %}
                    <a class="text-white" href="{% url 'baby:shoppingCartempty' %}"><span
                        class=" fs-1 fa-solid fa-cart-shopping btn btn-warning "></span></a>
                    {% endif %}
                    <div class="d-flex me-5">
                        <a href="{% url 'baby:logout' %}"
                            class="btn btn-outline-dark m-3  fs-1 withoutBorder text-light ">Salir
                            <i class="fa-solid fa-door-open"></i></a>
                    </div>
                    {% else %}
                    <div class="d-flex me-5">
                        <a href="{% url 'baby:login' %}"
                            class="btn btn-outline-dark m-3  fs-2 withoutBorder text-light " type="submit">Ingresar
                            <span class="fa-solid fa-user"></span></a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
    {% endblock %}
    {% block content%}

    {% endblock %}
    <script>
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-bottom-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
            }
        {% if messages %}
            {% for message in messages %}
                toastr.{{message.tags}}("{{ message }}")
            {% endfor %}
        {% endif %}
    </script>

</body>

</html>

baby/templates/baby/login.html
{% extends "baby/index.html" %}
{% block title%}Login{%endblock%}
{% block navbar %}
{% endblock %}
{% block content%}

<div class="bodylogin vh-100">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3>Ingresar</h3>
                <div class="d-flex justify-content-end social_icon">
                    <span><i class="fab fa-facebook-square"></i></span>
                    <span><i class="fab fa-google-plus-square"></i></span>
                    <span><i class="fab fa-twitter-square"></i></span>
                </div>
            </div>
            <div class="card-body">
                <form action="{% url 'baby:login'%}" method="post">
                    {% csrf_token %}
                    {{ formLogin.non_field_errors }}

                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ formLogin.correo }}
                        {% if field.errors %}

                        <div class="alert alert-danger mt-2" role="alert">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>

                        {% endif %}

                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>

                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa-solid fa-key"></i></span>
                        </div>
                        {{ formLogin.password}}
                        {% if field.errors %}

                        <div class="alert alert-danger mt-2" role="alert">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>

                        {% endif %}

                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>

                    <!--{% for field in formLogin %}
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ field }}
                        {% if field.errors %}

                        <div class="alert alert-danger mt-2" role="alert">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>

                        {% endif %}

                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    {% endfor %}-->

                    <div class="form-group">
                        <button class="btn float-right login_btn" type="submit">Login</button>
                    </div>
                    <div class="row align-items-center remember">
                        <input type="checkbox">Remember Me
                    </div>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center links">
                    Don't have an account?<a href="{% url 'baby:register'%}">Sign Up</a>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="#">Forgot your password?</a>
                </div>
            </div>
            </form>
        </div>

    </div>
</div>



<!--<div class=" vh-100 d-flex flex-column justify-content-center align-items-center">
    <div class="col-4">
        <div class="d-flex align-content-center justify-content-center">
            <h1>Login</h1>
        </div>
        <div class="container">
            <hr>
        </div>
    
        <div class="container">
            <form action="{% url 'books:login' %}" method="post">
    
                {% csrf_token %}
                {{ formLogin.non_field_errors }}
    
                {% for field in formLogin %}
                <div class="mb-3 row">
    
    
                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>
    
                    {% if field.errors %}
    
                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
    
                    {% endif %}
    
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}
    
                <div class="d-flex justify-content-center">
                    <button class="btn btn-primary " type="submit">Enviar</button>
                </div>
            </form>
    
        </div>

    </div>

</div>-->








{% endblock %}

baby/templates/baby/shoppingCartEmpty.html
{% extends "baby/index.html" %}
{% block title%}Carrito Vacio{%endblock%}
{% block content%}
<div class="d-flex justify-content-end ">
    <div class="vw-100 d-flex align-items-center">
        <div class="container-fluid mt-100 ">
            <div class="row">
                <div class="col-md-12 d-flex justify-content-center align-items-center ">
                    <div class="card  h-100 d-flex mb-5">
                        <div class="card-header bg-light ">
                            <h5>Aviso <i class="fa-solid fa-bullhorn"></i></h5>
                        </div>
                        <div class="card-body cart bg-light">
                            <div class="col-sm-12 empty-cart-cls text-center"> <img src="https://i.imgur.com/dCdflKN.png" width="160" height="160" class="img-fluid mb-4 mr-3">
                                <h3 class=""><strong>Tu carrito está vacío</strong></h3>
                                <h4>Añade un producto y dale un regalo a tu bebé <span class="fa-solid fa-face-grin-wink"></span> </h4> <a href="{% url 'baby:mainPage' %}" class="btn btn-primary cart-btn-transform m-3" data-abc="true">Volver a las compras!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-lg-4 bg-grey vh-100">
            
        </div>
    </div>
</section>


{% endblock %}

baby/templates/baby/showProductDetail.html
{% extends "baby/indexAdmin.html" %}
{% block title%}Product Detail{%endblock%}
{% block content%}
<div class="d-flex p-5 ">
    <div class="d-flex flex-column">
        <h1 class="m-3">{{producto.name}}</h1>
        <h3 class="m-3">Descripción: {{producto.description}}</h3>
        <h3 class="m-3">Precio: {{producto.price}}</h3>
        <h3 class="m-3">Talla: {{producto.get_size_display}}</h3>
        <h3 class="m-3">Stock: {{producto.stock}}</h3>
        <h3 class="m-3">Categoria: {{producto.prodCat}}</h3>
        <h3 class="m-3">Género: {{producto.get_prodGender_display}}</h3>
        <h3 class="m-3">Unidades vendidas: {{producto.cantVendidos}}</h3>
        <hr>
        <h3 class="m-3"> Fecha de creación: {{producto.created_at}}</h3>
        <h3 class="m-3">Fecha de modificación: {{producto.updated_at}}</h3>
        <a href="{% url 'baby:showProducts' %}" class="fa-solid fa-circle-arrow-left m-3 fs-1 text-decoration-none  "></a>
        <i class=""></i>
    </div>

    
    <div class="d-flex justify-content-center align-items-center">
        {% if producto.img %}
        <div class = "w-50">
            <img class="ms-5" src="{{ producto.img.url }}" alt="Error de carga, por favor actualizar">
        {% else %}
        </div>
        {% load static %}
        <img class="halfImage" src="{% static 'img/babyClothesAdd.jpg' %}" alt="Error de carga, por favor actualizar">
        {% endif %}

    </div>
</div>




{% endblock %}