app/urls.py
from django.urls import path     
from . import views_forms

app_name = 'books'

urlpatterns = [
    path('', views_forms.main, name='main' ),
    path('login', views_forms.login, name='login'),
    path('exit', views_forms.logout, name='logout'),
    path('books', views_forms.mybooks, name='mybooks'),
    path('books/<int:id>/delRelUsBK', views_forms.unFavourite, name='deleteRelBookUser'),
    path('books/<int:id>', views_forms.bookDetail, name='bookDetail'),
    path('books/<int:id>/delete', views_forms.delete, name='deleteBook'),
    path('books/<int:id>/relBookUser', views_forms.relationBookToUser, name='relBookUser'),



]

deseos/urls.py
from django.urls import path     
from . import views_forms

app_name = 'wishes'

urlpatterns = [
    path('', views_forms.main, name='main' ),
    path('login', views_forms.login, name='login'),
    path('exit', views_forms.logout, name='logout'),
    path('wishes', views_forms.mywishes, name='mywishes'),
    path('wishes/stats', views_forms.stats, name='stats'),
    path('wishes/new', views_forms.addWish, name='addWish'),
    path('wishes/edit/<int:id>', views_forms.editWish, name='editWish'),
    path('wishes/<int:id>/delete', views_forms.delete, name='deleteWish'),
    path('wishes/<int:id>/grantWishUser', views_forms.grantWish, name='relWishUser'),
    path('wishes/<int:id>/like', views_forms.likeWish, name='likeWish'),




]

librosFav/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('deseos/', include('deseos.urls')),
    path('ayudante/', include('ayudante.urls')),
    path('', include('baby.urls')),
]

deseos/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=50, unique=True)
    password = models.CharField(max_length=100, verbose_name='contrasenia')

    def __str__(self):
        return f'{self.first_name} , {self.last_name}'

class Wish(models.Model):
    item = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    wished_by = models.ForeignKey(User, related_name='wishes_uploaded', on_delete=models.CASCADE)
    granted = models.BooleanField(default=False)
    def __str__(self):
        return f'{self.item}'

class Like(models.Model):
    users = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE )
    wishes = models.ForeignKey(Wish, related_name='likes', on_delete=models.CASCADE)

deseos/templates/deseos/editWish.html
{% extends "app/index.html" %}
{% block title%}makeWish{%endblock%}
{% block content%}
<div class="d-flex justify-content-between bg-dark text-light ">

    <h1 class="m-4 "><span class="fa fa-user-circle"></span> Hello {{request.session.usuario.nombre}}
        {{request.session.usuario.apellido}}! Let's edit your wish!!</h1>
    <h1 class="m-4 "><a href="{% url 'wishes:logout' %}">Salir</a></h1>
</div>

<div class="w-75 d-flex justify-content-start p-5">
    <form action="" method="post">

        {% csrf_token %}
        {{ wishForm.non_field_errors }}

        {% for field in wishForm %}
        <div class="mb-3 row">


            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
            <div class="col-sm-9">
                {{ field }}
            </div>

            {% if field.errors %}

            <div class="alert alert-danger mt-2" role="alert">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>

            {% endif %}

            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <div class="container fs-3 d-flex justify-content-center">
            <div class="d-flex ">
                <a href="{% url 'wishes:mywishes' %}" class="btn btn-light m-1">Cancel</a>
            </div>
            <div class="d-flex ">
                <form action="" method="post">
                    <button class="btn btn-warning m-1" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </form>
</div>


{% endblock %}

deseos/templates/deseos/firstPage.html
{% extends "app/index.html" %}
{% block title%}addShow{%endblock%}
{% block content%}
<div class="d-flex justify-content-between bg-dark text-light ">

    <h1 class="m-4 "><span class="fa fa-user-circle"></span> Hello {{request.session.usuario.nombre}}
        {{request.session.usuario.apellido}}!</h1>
    <div class="d-flex align-items-center">
        <h1 class="m-2"><a href="{% url 'wishes:logout' %}">Logout</a></h1> 
        <h1 class="m-2"><a href="{% url 'wishes:stats' %}" class="btn btn-info fs-3">View Stats</a></h1>
        <h1 class="m-2"><a href="{% url 'wishes:addWish' %}" class="btn btn-warning fs-3">Make a Wish!</a></h1>
    </div>

</div>

<div class="d-flex m-1 justify-content-around ">

    <div class="d-flex flex-column w-50">

        <div class="container ">
            <div class="d-flex align-items-center py-3">
                <h1>My Wishes<span class="fa fa-book"></span></h1>
            </div>
            <table class="table table-striped col-10 ">
                <thead>
                    <tr>

                        <th scope="col">Item</th>
                        <th scope="col">Date Added</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="fs-5">
                    {% for wish in itemUserNoGranted%}

                    <tr>

                        <td>{{wish.item}}</td>
                        <td>{{wish.created_at}}</td>
                        <td class="d-flex align-items-center">
                            <a href="" class="mx-1 fa fa-trash btn btn-danger" data-bs-toggle="modal" data-bs-target="#myModal{{wish.id}}"></a>
                            <a href="{% url 'wishes:editWish' id=wish.id %} " class="mx-1 fa fa-pencil-square-o btn btn-info "></a>
                            <form action="{% url 'wishes:relWishUser' id=wish.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-warning mx-1">Granted!</button>
                            </form>
                        </td>

                                <!-- The Modal -->
                        <div class="modal fade" id="myModal{{wish.id}}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                    
                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h4 class="modal-title text-danger ">ALERTA</h4>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                    </div>
                    
                                    <!-- Modal body -->
                                    <div class="modal-body">
                                        Esta a punto de borrar: {{wish.item}}
                                    </div>
                    
                                    <!-- Modal footer -->
                                    <div class="modal-footer">
                                        <form action="{% url 'wishes:deleteWish' id=wish.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger" data-bs-dismiss="modal">Eliminar</button>
                                        </form>
                                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button>
                                    </div>
                    
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </tr>
                </tbody>
            </table>
        </div>

        <div class="container ">
            <div class="d-flex align-items-center py-3">
                <h1>Granted Wishes<span class="fa fa-book"></span></h1>
            </div>
            <table class="table table-striped col-10 ">
                <thead>
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">Wisher</th>
                        <th scope="col">Date Added</th>
                        <th scope="col">Date Granted</th>
                        <th scope="col">Likes</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="fs-5">
                    {% for wish in allItemsGranted%}
                        <tr>
                        <td>{{wish.item}}</td>
                        <td>{{wish.wished_by.first_name}} {{wish.wished_by.last_name}}</td>
                        <td>{{wish.created_at}}</td>
                        <td>{{wish.updated_at}}</td>
                        <td>{{wish.likes.all.count}}</td>
                        <td>  
                                                
                            <form action="{% url 'wishes:likeWish' id=wish.id %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-primary fa fa-thumbs-up" type="submit"></button>
                        </form></td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>



{% endblock %}

deseos/templates/deseos/main.html
{% extends "app/index.html" %}
{% block title%}addShow{%endblock%}
{% block content%}
<div class="container d-flex flex-column" >
    <h1 class=" m-3 text-center">Welcome! Sign in to make a Wish! <span class="fa fa-star text-warning  "></span></h1>
    <div class="container d-flex">

        <div class="container">
            <div class="d-flex align-content-center justify-content-center ">
                <h1 class="m-2">Register</h1>
            </div>
            <div class="container">
                <hr>
            </div>
            
            <div class="container pb-5">
                <form action="{% url 'wishes:main' %}" method="post">
            
                    {% csrf_token %}
                    {{ formRegister.non_field_errors }}
            
                    {% for field in formRegister %}
                    <div class="mb-3 row">
            
            
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-9">
                            {{ field }}
                        </div>
            
                        {% if field.errors %}
            
                        <div class="alert alert-danger mt-2" role="alert">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
            
                        {% endif %}
            
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    {% endfor %}
            
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-primary " type="submit">Enviar</button>
                    </div>
                </form>
            
            </div>
        </div>
        
        <div class="container">
            <div class="d-flex align-content-center justify-content-center ">
                <h1 class="m-2">Login</h1>
            </div>
            <div class="container">
                <hr>
            </div>
            
            <div class="container pb-5">
                <form action="{% url 'wishes:login' %}" method="post">
            
                    {% csrf_token %}
                    {{ formLogin.non_field_errors }}
            
                    {% for field in formLogin %}
                    <div class="mb-3 row">
            
            
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-9">
                            {{ field }}
                        </div>
            
                        {% if field.errors %}
            
                        <div class="alert alert-danger mt-2" role="alert">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
            
                        {% endif %}
            
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    {% endfor %}
            
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-primary " type="submit">Enviar</button>
                    </div>
                </form>
            
            </div>
        </div>
    </div>
</div>





{% endblock %}

deseos/templates/deseos/makeWish.html
{% extends "app/index.html" %}
{% block title%}makeWish{%endblock%}
{% block content%}
<div class="d-flex justify-content-between bg-dark text-light ">

    <h1 class="m-4 "><span class="fa fa-user-circle"></span> Hello {{request.session.usuario.nombre}}
        {{request.session.usuario.apellido}}! Make a Wish!!</h1>
    <h1 class="m-4 "><a href="{% url 'wishes:logout' %}">Salir</a></h1>
</div>

<div class="w-75 d-flex justify-content-start p-5">
    <form action="" method="post">

        {% csrf_token %}
        {{ wishForm.non_field_errors }}

        {% for field in wishForm %}
        <div class="mb-3 row">


            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
            <div class="col-sm-9">
                {{ field }}
            </div>

            {% if field.errors %}

            <div class="alert alert-danger mt-2" role="alert">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>

            {% endif %}

            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <div class="container fs-3 d-flex justify-content-center">
            <div class="d-flex ">
                <a href="{% url 'wishes:mywishes' %}" class="btn btn-light m-1">Cancel</a>
            </div>
            <div class="d-flex ">
                <form action="" method="post">
                    <button class="btn btn-warning m-1" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </form>
</div>


{% endblock %}