app/urls.py
from django.urls import path     
from . import views_forms

app_name = 'books'

urlpatterns = [
    path('', views_forms.main, name='main' ),
    path('login', views_forms.login, name='login'),
    path('exit', views_forms.logout, name='logout'),
    path('books', views_forms.mybooks, name='mybooks'),
    path('books/<int:id>/delRelUsBK', views_forms.unFavourite, name='deleteRelBookUser'),
    path('books/<int:id>', views_forms.bookDetail, name='bookDetail'),
    path('books/<int:id>/delete', views_forms.delete, name='deleteBook'),
    path('books/<int:id>/relBookUser', views_forms.relationBookToUser, name='relBookUser'),



]

librosFav/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('deseos/', include('deseos.urls')),
    path('ayudante/', include('ayudante.urls')),
    path('', include('baby.urls')),
]

app/templates/app/firstPage.html
{% extends "app/index.html" %}
{% block title%}addShow{%endblock%}
{% block content%}
<div class="d-flex justify-content-between bg-dark text-light ">

    <h1 class="m-4 "><span class="fa fa-user-circle"></span> Welcome {{request.session.usuario.nombre}}
        {{request.session.usuario.apellido}}</h1>
    <h1 class="m-4 "><a href="{% url 'books:logout' %}">Salir</a></h1>
</div>

<div class="d-flex m-1 justify-content-around ">
    <div class="w-25 align-items-center ">
        <div class="d-flex align-items-center py-3">
            <h1>Add a Favourite Book <span class="fa fa-book"></span></h1>
        </div>

        <form action="" method="post">

            {% csrf_token %}
            {{ bookForm.non_field_errors }}

            {% for field in bookForm %}
            <div class="mb-3 row">


                <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                <div class="col-sm-9">
                    {{ field }}
                </div>

                {% if field.errors %}

                <div class="alert alert-danger mt-2" role="alert">
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                </div>

                {% endif %}

                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
            {% endfor %}

            <div class="d-flex justify-content-center">
                <button class="btn btn-primary " type="submit">Enviar</button>
            </div>
        </form>

    </div>

    <div class="d-flex flex-column w-50">

        <div class="container ">
            <div class="d-flex align-items-center py-3">
                <h1>My Books<span class="fa fa-book"></span></h1>
            </div>
            <table class="table table-striped col-10 ">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Added by</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="fs-5">
                    {% for book in authorBooks%}

                    <tr>
                        <th scope="row">{{book.id}}</th>
                        <td><a href="{% url 'books:bookDetail' id=book.id %}">{{book.title}}</a></td>
                        <td>{{book.uploaded_by.first_name}} {{book.uploaded_by.last_name}}</td>
                        <td class="d-flex">
                            <button class="btn btn-warning fa fa-star-o" type="submit"></button>
                        </td>
                        {% endfor %}

                    </tr>
                </tbody>
            </table>
        </div>

        <div class="container ">
            <div class="d-flex align-items-center py-3">
                <h1>Other Books<span class="fa fa-book"></span></h1>
            </div>
            <table class="table table-striped col-10 ">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Added by</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="fs-5">
                    {% for book in otherBooks%}

                    <tr>
                        <th scope="row">{{book.id}}</th>
                        <td><a href="{% url 'books:bookDetail' id=book.id %}">{{book.title}}</a></td>
                        <td>{{book.uploaded_by.first_name}} {{book.uploaded_by.last_name}}</td>
                        <td class="d-flex">
                            <form action="{% url 'books:relBookUser' id=book.id %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-light fa fa-star-o" type="submit"></button>
                            </form>
                        

                        </td>
                        {% endfor %}

                    </tr>
                </tbody>
            </table>
        </div>
        <div class="container ">
            <div class="d-flex align-items-center py-3">
                <h1>My Favourites<span class="fa fa-book"></span></h1>
            </div>
            <table class="table table-striped col-10 ">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Added by</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="fs-5">
                    {% for book in favouritesBooks%}

                    <tr>
                        <th scope="row">{{book.id}}</th>
                        <td><a href="{% url 'books:bookDetail' id=book.id %}">{{book.title}}</a></td>
                        <td>{{book.uploaded_by.first_name}} {{book.uploaded_by.last_name}}</td>
                        <td class="d-flex">
                            <span class="btn btn-warning fa fa-star-o m-1"></span>
                            <form action="{% url 'books:deleteRelBookUser' id=book.id %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-danger fa fa-star-o m-1" type="submit"></button>
                            </form>
                        </td>
                        {% endfor %}

                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>



{% endblock %}

app/templates/app/main.html
{% extends "app/index.html" %}
{% block title%}addShow{%endblock%}
{% block content%}
<div class="container d-flex justify-content" >

    <div class="container">
        <div class="d-flex align-content-center justify-content-center ">
            <h1 class="m-4">Registro</h1>
        </div>
        <div class="container">
            <hr>
        </div>
        
        <div class="container pb-5">
            <form action="{% url 'books:main' %}" method="post">
        
                {% csrf_token %}
                {{ formRegister.non_field_errors }}
        
                {% for field in formRegister %}
                <div class="mb-3 row">
        
        
                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>
        
                    {% if field.errors %}
        
                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
        
                    {% endif %}
        
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}
        
                <div class="d-flex justify-content-center">
                    <button class="btn btn-primary " type="submit">Enviar</button>
                </div>
            </form>
        
        </div>
    </div>
    
    <div class="container">
        <div class="d-flex align-content-center justify-content-center ">
            <h1 class="m-4">Login</h1>
        </div>
        <div class="container">
            <hr>
        </div>
        
        <div class="container pb-5">
            <form action="{% url 'books:login' %}" method="post">
        
                {% csrf_token %}
                {{ formLogin.non_field_errors }}
        
                {% for field in formLogin %}
                <div class="mb-3 row">
        
        
                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>
        
                    {% if field.errors %}
        
                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
        
                    {% endif %}
        
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}
        
                <div class="d-flex justify-content-center">
                    <button class="btn btn-primary " type="submit">Enviar</button>
                </div>
            </form>
        
        </div>
    </div>
</div>





{% endblock %}

app/templates/app/showDetail.html
{% extends "app/index.html" %}

{% block title%}Book Detail{%endblock%}

{% block content%}
<div class="d-flex justify-content-between bg-dark text-light ">

    <h1 class="m-4 "><span class="fa fa-user-circle"></span> Welcome {{request.session.usuario.nombre}}
        {{request.session.usuario.apellido}}</h1>
    <h1 class="m-4 "><a href="{% url 'books:logout' %}">Logout</a></h1>
</div>
<div class="d-flex align-content-center justify-content-end me-2">
    <h1><a href="{% url 'books:mybooks' %}">Go Back</a></h1>
</div>

<div class="container">
    <h2>{{book.title}} <span class="fa fa-video-camera"></span></h2>
    <div class="fs-4 ">
        <p>Description: {{book.description}}</p>
    </div>
    <div class="fs-4">
        <p>Added by: {{book.uploaded_by.first_name}} {{book.uploaded_by.last_name}}</p>
    </div>
    <div class="fs-4 ">
        <p>Added on: {{book.created_at}}</p>
    </div>
    <div class="fs-4 ">
        <p>Last Updated: {{book.updated_at}}</p>
    </div>
    <div class="fs-4 ">
        <h4>Users Who Like This Book</h4>
        {% for person in peopleWhoLikeBook %}
        <ul>
            <li>{{person.first_name}} {{person.last_name}}</li>
        </ul>
        {% endfor %}
    </div>
    
</div>




{% endblock %}

app/templates/app/showDetailMine.html
{% extends "app/index.html" %}

{% block title%}Book Detail{%endblock%}

{% block content%}
<div class="d-flex justify-content-between bg-dark text-light ">

    <h1 class="m-4 "><span class="fa fa-user-circle"></span> Welcome {{request.session.usuario.nombre}}
        {{request.session.usuario.apellido}}</h1>
    <h1 class="m-4 "><a href="{% url 'books:logout' %}">Logout</a></h1>
</div>
<div class="d-flex align-content-center justify-content-end me-2">
    <h1><a href="{% url 'books:mybooks' %}">Go Back</a></h1>
</div>

<div class="container d-flex justify-content-start">
    <form action="" method="post">

        {% csrf_token %}
        {{ bookForm.non_field_errors }}

        {% for field in bookForm %}
        <div class="mb-3 row">


            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
            <div class="col-sm-9">
                {{ field }}
            </div>

            {% if field.errors %}

            <div class="alert alert-danger mt-2" role="alert">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>

            {% endif %}

            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <div class="container fs-3">
            <p>Added by: {{book.uploaded_by.first_name}} {{book.uploaded_by.last_name}}</p>
        </div>
        <div class="container fs-3 ">
            <p>Added on: {{book.created_at}}</p>
        </div>
        <div class="container fs-3 ">
            <p>Last Updated: {{book.updated_at}}</p>
        </div>
        <div class="fs-4 ">
            <h4>Users Who Like This Book</h4>
            {% for person in peopleWhoLikeBook %}
            <ul>
                <li>{{person.first_name}} {{person.last_name}}</li>
            </ul>
            {% endfor %}
        </div>
        <div class="container fs-3 d-flex">
            <div class="d-flex justify-content-center">
                <button class="btn btn-warning " type="submit">Editar</button>
            </div>
        </div>
    </form>
    <div class="">
        <button class="mx-3 btn btn-danger mx-1 fa fa-trash-o" type="submit" data-bs-toggle="modal"
            data-bs-target="#myModal{{book.id}}"></button>
        <!-- The Modal -->
        <div class="modal fade" id="myModal{{book.id}}">
            <div class="modal-dialog">
                <div class="modal-content">
    
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title text-danger ">ALERTA</h4>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>
    
                    <!-- Modal body -->
                    <div class="modal-body">
                        Esta a punto de borrar: {{book.title}}
                    </div>
    
                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <form action="{% url 'books:deleteBook' id=book.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" data-bs-dismiss="modal">Eliminar</button>
                        </form>
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button>
                    </div>
    
                </div>
            </div>
        </div>

    </div>
</div>




{% endblock %}